import styles from '../styles/sudoku.module.css'
import React from 'react';
import Link from 'next/link';
import Image from 'next/image';
import Head from 'next/head'
import Sudoku from '../sudoku/sudoku'
import Wordoku from '../sudoku/wordoku';
import UploadPuzzle from '../sudoku/uploadPuzzle';
import { useRouter } from 'next/router';
import Dropdown from 'react-bootstrap/Dropdown';
import {getItem} from './localStorage';
import { useState, useEffect } from 'react';

export default function sudokuPage() {

  const [user, setUser] = useState({username: ""});

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const user = getItem('user');
      if (user) {
           setUser(JSON.parse(user));
      }
  }
  }, [])

  const router = useRouter();

  return (
    <div className={styles.container}>

      <Head>
        <title>Create {router.query.variant == "sudoku" ? "Sudoku" : "Wordoku"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <nav class="navbar sticky-top" style={{backgroundImage: "linear-gradient(160deg, #ea730f 0%, #fcc300 100%)", boxShadow: "0px 0px 5px #9e8a67"}}>
        <div class="container-fluid">
          <span className={styles.logo}>
            <Link className={styles.icon} href="./">
              <Image  src="/favicon.png" alt="Logo" width={50} height={50} class="d-inline-block align-text-top"/>
            </Link>

            <Link href="./home">
              <div className={styles.brand}>
                Solvesudo
              </div>
            </Link>
          </span>

          <Dropdown className={styles.menuDropdown}>
            <Dropdown.Toggle className={styles.dropHead}>
              Menu
            </Dropdown.Toggle>

            <Dropdown.Menu className={styles.dropItem}>
              <Dropdown.Item className={styles.dropItems} href="./puzzle-list/sudoku">Play Sudoku</Dropdown.Item>
              <Dropdown.Item className={styles.dropItems} href="./puzzle-list/wordoku">Play Wordoku</Dropdown.Item>
              <Dropdown.Item className={styles.dropItems} href="./create-sudoku?variant=sudoku">Create Sudoku</Dropdown.Item>
              <Dropdown.Item className={styles.dropItems} href="./create-sudoku?variant=wordoku">Create Wordoku</Dropdown.Item>
              <Dropdown.Item className={styles.dropItems} href="./leaderboard">View Leaderboard</Dropdown.Item>
            </Dropdown.Menu>
          </Dropdown>

        </div>
      </nav>

      <main className={styles.main}>

        <div className={styles.instructions}>
          <p>Create or upload your own sudoku here!</p>
          <p>To create, simply input your sudoku into the grid, select a difficulty and click "Save Sudoku".</p>
          <p>To upload a sudoku, click "Browse", selct your sudoku file and click "Submit"</p>
        </div>

        <div className={styles.card}>
          {
            router.query.variant == "sudoku"
            ?
            <Sudoku author={user.user_id}/>
            :
            <Wordoku author={user.user_id}/>
          }
          <UploadPuzzle/>
        </div>

      </main>

      <footer className={styles.footer}>
        
      </footer>


    </div>
  )
}

