import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/home.module.css'
import React, { useEffect } from 'react';
import Link from 'next/link';
import Sudoku from '../sudoku/sudoku'
import login from './login';
import { useState } from 'react';
import { setItem, getItem } from './localStorage';

export default function HomePage() {

  const [user, setUser] = useState({username: ""});

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const user = getItem('user');
      if (user) {
           setUser(JSON.parse(user));
      }
 }
  }, [])


  return (
    <div className={styles.container}>

      <Head>
        <title>Solvesudo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Welcome {(user?.display_name != null && user?.display_name) ? user.display_name : user.username}
        </h1>

        <h1 className={styles.text}>
          <Link href="./puzzle-list/sudoku">Play Sudoku</Link>
        </h1>

        <h1 className={styles.text}>
          <Link href="./puzzle-list/wordoku">Play Wordoku</Link>
        </h1>
        
        <h1 className={styles.text}>
          <Link href="./create-sudoku?variant=sudoku">Create Sudoku</Link>
        </h1>

        <h1 className={styles.text}>
          <Link href="./create-sudoku?variant=wordoku">Create Wordoku</Link>
        </h1>

        <h1 className={styles.text}>
          <Link href={`/user_profile?user_id=${user.user_id}`}>View Profile</Link>
        </h1>

        <h1 className={styles.text}>
          <Link href="./leaderboard">View Leaderboard</Link>
        </h1>

        <span className={styles.logo}>
            <Image src="/favicon.png" alt="Logo" width={100} height={100} />
        </span>
      </main>

      <footer className={styles.footer}>
          Created by Group 8
      </footer>
    </div>
  )
}
