import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/home.module.css'
import React from 'react';
import Link from 'next/link';
import Sudoku from '../sudoku/sudoku'

export default function Home() {

  return (
    <div className={styles.container}>

      <Head>
        <title>Solvesudo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>

      <h1 className={styles.title}>
            Welcome to Solvesudo
          </h1>
        <h1 className={styles.text}>
          <Link href="./register">Register</Link>
        </h1>
        
        <h1 className={styles.text}>
          <Link href="./login">Login</Link>
        </h1>

        <span className={styles.logo}>
            <Image src="/favicon.png" alt="Logo" width={100} height={100} />
        </span>
      </main>

      <footer className={styles.footer}>
          created by group 8
      </footer>
    </div>
  )
}