import styles from '../styles/admin.module.css'
import React from 'react';
import Link from 'next/link';
import Image from 'next/image';
import Head from 'next/head';
import Table from 'react-bootstrap/Table'
import Dropdown from 'react-bootstrap/Dropdown';

import { all_users, get_user_xp } from '../database';

export async function getServerSideProps(context) {
  const users = await all_users();
  const xp_promise = users.map(user => {
    return get_user_xp(user._id).then(xp => {
      return {
        name: user.display_name ? user.display_name : user.username,
        xp: xp
      }
    })
  });

  const data = await Promise.all(xp_promise);

  return {
    props: {
      data: data
    }
  }
}

export default function LeaderboardPage(props) {

  return (
    <div className={styles.container}>

     <Head>
        <title>Leaderboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <nav class="navbar sticky-top" style={{backgroundImage: "linear-gradient(160deg, #ea730f 0%, #fcc300 100%)", boxShadow: "0px 0px 5px #9e8a67"}}>
        <div class="container-fluid">
          <span className={styles.logo}>
            <Link className={styles.icon} href="./">
              <Image  src="/favicon.png" alt="Logo" width={50} height={50} class="d-inline-block align-text-top"/>
            </Link>

            <Link href="./home">
              <div className={styles.brand}>
                Solvesudo
              </div>
            </Link>
          </span>

          <Dropdown className={styles.menuDropdown}>
            <Dropdown.Toggle className={styles.dropHead}>
              Menu
            </Dropdown.Toggle>

            <Dropdown.Menu className={styles.dropItem}>
              <Dropdown.Item className={styles.dropItems} href="./puzzle-list/sudoku">Play Sudoku</Dropdown.Item>
              <Dropdown.Item className={styles.dropItems} href="./puzzle-list/wordoku">Play Wordoku</Dropdown.Item>
              <Dropdown.Item className={styles.dropItems} href="./create-sudoku?variant=sudoku">Create Sudoku</Dropdown.Item>
              <Dropdown.Item className={styles.dropItems} href="./create-sudoku?variant=wordoku">Create Wordoku</Dropdown.Item>
              <Dropdown.Item className={styles.dropItems} href="./leaderboard">View Leaderboard</Dropdown.Item>
            </Dropdown.Menu>
          </Dropdown>

        </div>
      </nav>


      <main className={styles.main}>
      <div className={styles.table_page_container}>

      <br></br>
      <br></br>
      <h1>Leaderboard</h1>
      
      
      
 
      <div>
      <Table>
        <thead>
        <tr>
          <th>#</th>
          <th>Username</th>
          <th>Total XP</th>
        </tr>
        </thead>
        <tbody>
          {props.data.sort((userA, userB) => userB.xp - userA.xp).map((user, index) => <tr>
            <td>{index}</td><td>{user.name}</td><td>{user.xp}</td>
          </tr>)}
        </tbody>
      </Table>
      
    </div>
  
  
    </div>
</main>

    </div>
  )
}