import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/admin.module.css'
import Link from 'next/link';
import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/router'
import { GetServerSideProps } from 'next'
import Dropdown from 'react-bootstrap/Dropdown';
import { get_local_user, get_user_xp, get_puzzles_completed, get_puzzle } from '/database';

export async function getServerSideProps(context) {

  const { user_id } = context.query;

  const user_data = await get_local_user(user_id);
  const xp = await get_user_xp(user_id);
  const solved = await get_puzzles_completed(user_id);

  const puzzle_names = [];

  for (const obj of solved) {
    const puzzleId = obj.puzzle_id;
    const puzzle = await get_puzzle(puzzleId);
    puzzle_names.push(puzzle.name);
  }

  console.log(puzzle_names);

  return {
    props: { user_data, xp, solved: puzzle_names },
  };
}

export default function ProfilePage(props) {

  const { user_data, xp, solved } = props;
  const listPuzzles = solved.map((value, index) => (
    <li key={index}>{value}</li>
  ));

  return (
    <div className={styles.container}>

      <Head>
        <title>User Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <nav class="navbar sticky-top" style={{backgroundImage: "linear-gradient(160deg, #ea730f 0%, #fcc300 100%)", boxShadow: "0px 0px 5px #9e8a67"}}>
        <div class="container-fluid">
          <span className={styles.logo}>
            <Link className={styles.icon} href="./">
              <Image  src="/favicon.png" alt="Logo" width={50} height={50} class="d-inline-block align-text-top"/>
            </Link>

            <Link href="./home">
              <div className={styles.brand}>
                Solvesudo
              </div>
            </Link>
          </span>

          <Dropdown className={styles.menuDropdown}>
            <Dropdown.Toggle className={styles.dropHead}>
              Menu
            </Dropdown.Toggle>

            <Dropdown.Menu className={styles.dropItem}>
              <Dropdown.Item className={styles.dropItems} href="./puzzle-list/sudoku">Play Sudoku</Dropdown.Item>
              <Dropdown.Item className={styles.dropItems} href="./puzzle-list/wordoku">Play Wordoku</Dropdown.Item>
              <Dropdown.Item className={styles.dropItems} href="./create-sudoku?variant=sudoku">Create Sudoku</Dropdown.Item>
              <Dropdown.Item className={styles.dropItems} href="./create-sudoku?variant=wordoku">Create Wordoku</Dropdown.Item>
              <Dropdown.Item className={styles.dropItems} href="./leaderboard">View Leaderboard</Dropdown.Item>
            </Dropdown.Menu>
          </Dropdown>

        </div>
      </nav>

      <main className={styles.main}>
      
      <div className={styles.content_container}>
      <div className={styles.transparent_box}>

        <h1>My details</h1>
        <br></br>
        <img src={user_data.avatar_url ? props.data.avatar_url : "/avatar.png"} alt="avatar" width={150} height={150}></img>
        <br></br>
        <br></br>
        <h3 className={styles.text}>Username - {user_data.username}</h3>
        <h3 className={styles.text}>Email address - {user_data.email}</h3>
        <h3 className={styles.text}>Rank - {xp}</h3>
        <h3 className={styles.text}>Solved - {solved.length}</h3>
        

      </div>
     </div>

     <div className={styles.content_container}>
      <div className={styles.transparent_box}>

        <h1>Puzzles solved </h1>

        <br></br>

        <ul className={styles.text}>
        {listPuzzles}
        </ul>
       
        </div>
      </div>
  

      </main>

    </div>
  )
}
